/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tolvgx_helloworld_JNIUtils */

#ifndef _Included_com_tolvgx_helloworld_JNIUtils
#define _Included_com_tolvgx_helloworld_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tolvgx_helloworld_JNIUtils
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tolvgx_helloworld_JNIUtils_helloFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
